export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const DELETE_ALERT = 'DELETE_ALERT';
export const ADD_ALERT = 'ADD_ALERT';
export const DELETE_ALL_ALERT = 'DELETE_ALL_ALERT';

export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const CLEAR_MESSAGES ='CLEAR_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';

export const SOCKET_CONNECT ='SOCKET_CONNECT';
export const SOCKET_DISCONNECT ='SOCKET_DISCONNECT';


export const FETCH_MEMBERS = 'FETCH_MEMBERS';
export const CLEAR_MEMBERS = 'CLEAR_MEMBERS';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const DESTROY_DIALOG = 'DESTROY_DIALOG';

export const REPLY_MESSAGE = 'REPLY_MESSAGE';
export const CANCEL_REPLY_MESSAGE = 'CANCEL_REPLY_MESSAGE';



